name = "mai2026"
main = "worker.js"
account_id = "a834d73c0d9e7a4e55b5aa08e7b48317"
compatibility_date = "2026-10-04"
workers_dev = true

[assets]
directory = "."
binding = "ASSETS"
run_worker_first = ["/api/*", "/boss"]

[observability]
enabled = true

[observability.traces]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "mai2026-user-data"
database_id = "950b2ace-23be-4124-a9c4-f0ae74fa3631"
migrations_dir = "migrations"
